apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tracing

resources:
- tempo-stack.yaml

commonLabels:
  app: tempo-stack
  component: observability

images:
- name: grafana/tempo
  newTag: 2.3.0
- name: otel/opentelemetry-collector-contrib
  newTag: 0.103.0