import {
  RadioTower as IconRadioTower,
  AlertCircle as LcAlertCircle,
  AlertTriangle as LcAlertTriangle,
  Webhook as IconWebhook,
  ArrowLeftRight as IconArrowLeftRight,
  CalendarDays as IconCalendarDays,
  Camera as LcCamera,
  Check as LcCheck,
  ChevronRight as LcChevronRight,
  ClipboardList as LcClipboardList,
  Crown as IconCrown,
  Download as LcDownload,
  Eye as LcEye,
  FileText as IconFileText,
  FileOutput as IconFileOutput,
  Upload as IconUpload,
  Forklift as LcForklift,
  Gauge as LcGauge,
  Key as LcKey,
  LayoutGrid as LcLayoutGrid,
  PanelLeft as IconPanelLeft,
  Lock as LcLock,
  LogOut as IconLogOut,
  Menu as LcMenu,
  Moon as LcMoon,
  Package as LcPackage,
  Paperclip as LcPaperclip,
  Pencil as LcPencil,
  PlaneTakeoff as IconPlaneTakeoff,
  Plus as LcPlus,
  RefreshCw as IconRefreshCw,
  Route as LcRoute,
  Scale as LcScale,
  Search as LcSearch,
  Settings as LcSettings,
  Shield as IconShield,
  ShieldAlert as IconShieldAlert,
  Sun as LcSun,
  Trash2 as IconTrash2,
  User as LcUser,
  Users as LcUsers,
  X as LcX,
  Store as LcStore
} from 'lucide-vue-next'

export const lucideIcons = {
  AirTrafficControl: IconRadioTower,
  AlertCircle: LcAlertCircle,
  AlertTriangle: LcAlertTriangle,
  Api: IconWebhook,
  ArrowsExchange: IconArrowLeftRight,
  CalendarEvent: IconCalendarDays,
  Camera: LcCamera,
  Check: LcCheck,
  ChevronRight: LcChevronRight,
  ClipboardList: LcClipboardList,
  CrownFilled: IconCrown,
  Download: LcDownload,
  Eye: LcEye,
  FileDescription: IconFileText,
  FileExport: IconFileOutput,
  FileInvoice: IconFileText,
  FileUpload: IconUpload,
  Forklift: LcForklift,
  Gauge: LcGauge,
  Key: LcKey,
  LayoutGrid: LcLayoutGrid,
  LayoutSidebarFilled: IconPanelLeft,
  Lock: LcLock,
  Logout: IconLogOut,
  Menu: LcMenu,
  Moon: LcMoon,
  Package: LcPackage,
  Paperclip: LcPaperclip,
  Pencil: LcPencil,
  PlaneDeparture: IconPlaneTakeoff,
  Plus: LcPlus,
  Refresh: IconRefreshCw,
  Route: LcRoute,
  Scale: LcScale,
  Search: LcSearch,
  Settings: LcSettings,
  ShieldLock: IconShield,
  ShieldAlert: IconShieldAlert,
  Sun: LcSun,
  Trash: IconTrash2,
  User: LcUser,
  Users: LcUsers,
  X: LcX,
  BuildingStore: LcStore
}