import {
  RadioTower as IconRadioTower,
  AlertCircle as LcAlertCircle,
  AlertTriangle as LcAlertTriangle,
  BarChart as LcBarChart,
  Bell as LcBell,
  BookOpen as LcBookOpen,
  CheckCheck as LcCheckCheck,
  Webhook as IconWebhook,
  ArrowLeftRight as IconArrowLeftRight,
  CalendarDays as IconCalendarDays,
  Camera as LcCamera,
  Check as LcCheck,
  CheckCircle as LcCheckCircle,
  ChevronRight as LcChevronRight,
  CircleX as LcClose,
  ClipboardList as LcClipboardList,
  Code as LcCode,
  Crown as IconCrown,
  Download as LcDownload,
  Eye as LcEye,
  File as LcFile,
  FileText as IconFileText,
  FileOutput as IconFileOutput,
  Upload as IconUpload,
  Forklift as LcForklift,
  Gauge as LcGauge,
  Inbox as LcInbox,
  Info as LcInfo,
  Key as LcKey,
  LayoutGrid as LcLayoutGrid,
  PanelLeft as IconPanelLeft,
  Lock as LcLock,
  LogOut as IconLogOut,
  Menu as LcMenu,
  Minus as LcMinus,
  Moon as LcMoon,
  Package as LcPackage,
  Paperclip as LcPaperclip,
  Pencil as LcPencil,
  PieChart as LcPieChart,
  PlaneTakeoff as IconPlaneTakeoff,
  PlaneLanding as IconPlaneLanding,
  Plus as LcPlus,
  RefreshCw as IconRefreshCw,
  Route as LcRoute,
  Scale as LcScale,
  Search as LcSearch,
  Send as LcSend,
  Settings as LcSettings,
  Shield as IconShield,
  ShieldAlert as IconShieldAlert,
  Boxes as LcBoxes,
  Sun as LcSun,
  Trash2 as IconTrash2,
  TrendingDown as LcTrendingDown,
  TrendingUp as LcTrendingUp,
  Truck as LcTruck,
  User as LcUser,
  Users as LcUsers,
  X as LcX,
  Store as LcStore
} from 'lucide-vue-next'

export const lucideIcons = {
  AirTrafficControl: IconRadioTower,
  AlertCircle: LcAlertCircle,
  AlertTriangle: LcAlertTriangle,
  Api: IconWebhook,
  ArrowsExchange: IconArrowLeftRight,
  BarChart: LcBarChart,
  Bell: LcBell,
  Book: LcBookOpen,
  CheckCheck: LcCheckCheck,
  CalendarEvent: IconCalendarDays,
  Camera: LcCamera,
  ChartBar: LcBarChart,
  ChartPie: LcPieChart,
  Check: LcCheck,
  CheckCircle: LcCheckCircle,
  ChevronRight: LcChevronRight,
  Close: LcClose,
  ClipboardList: LcClipboardList,
  Code: LcCode,
  CrownFilled: IconCrown,
  Cog: LcSettings,
  Download: LcDownload,
  Eye: LcEye,
  File: LcFile,
  FileDescription: IconFileText,
  FileExport: IconFileOutput,
  FileInvoice: IconFileText,
  FileUpload: IconUpload,
  Forklift: LcForklift,
  Gauge: LcGauge,
  Inbox: LcInbox,
  Info: LcInfo,
  Key: LcKey,
  LayoutGrid: LcLayoutGrid,
  LayoutSidebarFilled: IconPanelLeft,
  Lock: LcLock,
  Logout: IconLogOut,
  Menu: LcMenu,
  Minus: LcMinus,
  Moon: LcMoon,
  Package: LcPackage,
  Paperclip: LcPaperclip,
  Pencil: LcPencil,
  PlaneDeparture: IconPlaneTakeoff,
  PlaneLanding: IconPlaneLanding,
  Plus: LcPlus,
  Refresh: IconRefreshCw,
  Route: LcRoute,
  Scale: LcScale,
  Search: LcSearch,
  Send: LcSend,
  Settings: LcSettings,
  Shield: IconShield,
  ShieldLock: IconShield,
  ShieldAlert: IconShieldAlert,
  Sun: LcSun,
  ThLarge: LcLayoutGrid,
  Pallet: LcBoxes,
  Trash: IconTrash2,
  TrendingDown: LcTrendingDown,
  TrendingUp: LcTrendingUp,
  Truck: LcTruck,
  User: LcUser,
  Users: LcUsers,
  X: LcX,
  BuildingStore: LcStore
}