import {
  IconAirTrafficControl,
  IconAlertCircle,
  IconAlertTriangle,
  IconApi,
  IconBell,
  IconBook,
  IconChecks,
  IconArrowsExchange,
  IconCalendarEvent,
  IconCamera,
  IconChartBar,
  IconChartPie,
  IconCheck,
  IconChevronRight,
  IconCircleCheck,
  IconClipboardList,
  IconCode,
  IconCrownFilled,
  IconDownload,
  IconEye,
  IconFile,
  IconFileDescription,
  IconFileExport,
  IconFileInvoice,
  IconFileUpload,
  IconForklift,
  IconGauge,
  IconInbox,
  IconInfoCircle,
  IconKey,
  IconLayoutGrid,
  IconLayoutSidebarFilled,
  IconLock,
  IconLogout,
  IconMenu,
  IconMinus,
  IconMoon,
  IconPackage,
  IconPaperclip,
  IconPencil,
IconPlaneDeparture,
  IconPlaneArrival,
  IconPlus,
  IconRefresh,
  IconRoute,
  IconScale,
  IconSearch,
  IconSend,
  IconSettings,
  IconShield,
  IconShieldLock,
  IconShieldExclamation,
  IconStack2,
  IconSun,
  IconTrash,
  IconTrendingDown,
  IconTrendingUp,
  IconTruck,
  IconUser,
  IconUsers,
  IconX,
  IconBuildingStore
} from '@tabler/icons-vue'

export const tablerIcons = {
  AirTrafficControl: IconAirTrafficControl,
  AlertCircle: IconAlertCircle,
  AlertTriangle: IconAlertTriangle,
  Api: IconApi,
  ArrowsExchange: IconArrowsExchange,
  Bell: IconBell,
  Book: IconBook,
  CheckCheck: IconChecks,
  CalendarEvent: IconCalendarEvent,
  Camera: IconCamera,
  ChartBar: IconChartBar,
  ChartPie: IconChartPie,
  Check: IconCheck,
  CheckCircle: IconCircleCheck,
  ChevronRight: IconChevronRight,
  ClipboardList: IconClipboardList,
  Close: IconX,
  Code: IconCode,
  CrownFilled: IconCrownFilled,
  Cog: IconSettings,
  Download: IconDownload,
  Eye: IconEye,
  File: IconFile,
  FileDescription: IconFileDescription,
  FileExport: IconFileExport,
  FileInvoice: IconFileInvoice,
  FileUpload: IconFileUpload,
  Forklift: IconForklift,
  Gauge: IconGauge,
  Inbox: IconInbox,
  Info: IconInfoCircle,
  Key: IconKey,
  LayoutGrid: IconLayoutGrid,
  LayoutSidebarFilled: IconLayoutSidebarFilled,
  Lock: IconLock,
  Logout: IconLogout,
  Menu: IconMenu,
  Minus: IconMinus,
  Moon: IconMoon,
  Package: IconPackage,
  Paperclip: IconPaperclip,
  Pencil: IconPencil,
  PlaneDeparture: IconPlaneDeparture,
  PlaneLanding: IconPlaneArrival,
  Plus: IconPlus,
  Refresh: IconRefresh,
  Route: IconRoute,
  Scale: IconScale,
  Search: IconSearch,
  Send: IconSend,
  Settings: IconSettings,
  Shield: IconShield,
  ShieldLock: IconShieldLock,
  ShieldAlert: IconShieldExclamation,
  Sun: IconSun,
  ThLarge: IconLayoutGrid,
  Pallet: IconStack2,
  Trash: IconTrash,
  TrendingDown: IconTrendingDown,
  TrendingUp: IconTrendingUp,
  Truck: IconTruck,
  User: IconUser,
  Users: IconUsers,
  X: IconX,
  BuildingStore: IconBuildingStore
}