import {
  IconAirTrafficControl,
  IconAlertCircle,
  IconAlertTriangle,
  IconApi,
  IconArrowsExchange,
  IconCalendarEvent,
  IconCamera,
  IconCheck,
  IconChevronRight,
  IconClipboardList,
  IconCrownFilled,
  IconDownload,
  IconEye,
  IconFileDescription,
  IconFileExport,
  IconFileInvoice,
  IconFileUpload,
  IconForklift,
  IconGauge,
  IconKey,
  IconLayoutGrid,
  IconLayoutSidebarFilled,
  IconLock,
  IconLogout,
  IconMenu,
  IconMoon,
  IconPackage,
  IconPaperclip,
  IconPencil,
  IconPlaneDeparture,
  IconPlus,
  IconRefresh,
  IconRoute,
  IconScale,
  IconSearch,
  IconSettings,
  IconShieldLock,
  IconSun,
  IconTrash,
  IconUser,
  IconUsers,
  IconX,
  IconBuildingStore
} from '@tabler/icons-vue'

export const tablerIcons = {
  AirTrafficControl: IconAirTrafficControl,
  AlertCircle: IconAlertCircle,
  AlertTriangle: IconAlertTriangle,
  Api: IconApi,
  ArrowsExchange: IconArrowsExchange,
  CalendarEvent: IconCalendarEvent,
  Camera: IconCamera,
  Check: IconCheck,
  ChevronRight: IconChevronRight,
  ClipboardList: IconClipboardList,
  CrownFilled: IconCrownFilled,
  Download: IconDownload,
  Eye: IconEye,
  FileDescription: IconFileDescription,
  FileExport: IconFileExport,
  FileInvoice: IconFileInvoice,
  FileUpload: IconFileUpload,
  Forklift: IconForklift,
  Gauge: IconGauge,
  Key: IconKey,
  LayoutGrid: IconLayoutGrid,
  LayoutSidebarFilled: IconLayoutSidebarFilled,
  Lock: IconLock,
  Logout: IconLogout,
  Menu: IconMenu,
  Moon: IconMoon,
  Package: IconPackage,
  Paperclip: IconPaperclip,
  Pencil: IconPencil,
  PlaneDeparture: IconPlaneDeparture,
  Plus: IconPlus,
  Refresh: IconRefresh,
  Route: IconRoute,
  Scale: IconScale,
  Search: IconSearch,
  Settings: IconSettings,
  ShieldLock: IconShieldLock,
  ShieldAlert: IconShieldAlert,
  Sun: IconSun,
  Trash: IconTrash,
  User: IconUser,
  Users: IconUsers,
  X: IconX,
  BuildingStore: IconBuildingStore
}