apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: external-secrets

resources:
- externalsecrets-stack.yaml

commonLabels:
  app: external-secrets
  component: secrets-management