import { mdiRadar, mdiAlertCircle, mdiAlert, mdiApi, mdiSwapHorizontal, mdiCalendarMonth, mdiCamera, mdiCheck, mdiChevronRight, mdiClipboardList, mdiCrown, mdiDownload, mdiEye, mdiFileDocument, mdiFileExport, mdiReceiptText, mdiFileUpload, mdiForklift, mdiGauge, mdiKey, mdiViewGrid, mdiPageLayoutSidebarLeft, mdiLock, mdiLogout, mdiMenu, mdiWeatherNight, mdiPackageVariant, mdiPaperclip, mdiPencil, mdiAirplaneTakeoff, mdiPlus, mdiRefresh, mdiRoutes, mdiScale, mdiMagnify, mdiCog, mdiShieldLock, mdiShieldAlert, mdiWeatherSunny, mdiDelete, mdiAccount, mdiAccountGroup, mdiClose, mdiStore } from '@mdi/js'
import { mdiIcon } from './utils/mdiIcon'

const md = (path) => mdiIcon(path)

export const mdiIcons = {
  AirTrafficControl: md(mdiRadar),
  AlertCircle: md(mdiAlertCircle),
  AlertTriangle: md(mdiAlert),
  Api: md(mdiApi),
  ArrowsExchange: md(mdiSwapHorizontal),
  CalendarEvent: md(mdiCalendarMonth),
  Camera: md(mdiCamera),
  Check: md(mdiCheck),
  ChevronRight: md(mdiChevronRight),
  ClipboardList: md(mdiClipboardList),
  CrownFilled: md(mdiCrown),
  Download: md(mdiDownload),
  Eye: md(mdiEye),
  FileDescription: md(mdiFileDocument),
  FileExport: md(mdiFileExport),
  FileInvoice: md(mdiReceiptText),
  FileUpload: md(mdiFileUpload),
  Forklift: md(mdiForklift),
  Gauge: md(mdiGauge),
  Key: md(mdiKey),
  LayoutGrid: md(mdiViewGrid),
  LayoutSidebarFilled: md(mdiPageLayoutSidebarLeft),
  Lock: md(mdiLock),
  Logout: md(mdiLogout),
  Menu: md(mdiMenu),
  Moon: md(mdiWeatherNight),
  Package: md(mdiPackageVariant),
  Paperclip: md(mdiPaperclip),
  Pencil: md(mdiPencil),
  PlaneDeparture: md(mdiAirplaneTakeoff),
  Plus: md(mdiPlus),
  Refresh: md(mdiRefresh),
  Route: md(mdiRoutes),
  Scale: md(mdiScale),
  Search: md(mdiMagnify),
  Settings: md(mdiCog),
  ShieldLock: md(mdiShieldLock),
  ShieldAlert: md(mdiShieldAlert),
  Sun: md(mdiWeatherSunny),
  Trash: md(mdiDelete),
  User: md(mdiAccount),
  Users: md(mdiAccountGroup),
  X: md(mdiClose),
  BuildingStore: md(mdiStore)
}