import { mdiRadar, mdiAlertCircle, mdiAlert, mdiBell, mdiChartBar, mdiChartPie, mdiCheckAll, mdiApi, mdiSwapHorizontal, mdiCalendarMonth, mdiCamera, mdiCheck, mdiCheckCircle, mdiChevronRight, mdiClipboardList, mdiCodeTags, mdiCrown, mdiDownload, mdiEye, mdiBookOpen, mdiInbox, mdiSend, mdiFile, mdiShippingPallet, mdiFileDocument, mdiFileExport, mdiReceiptText, mdiFileUpload, mdiForklift, mdiGauge, mdiInformation, mdiKey, mdiViewGrid, mdiPageLayoutSidebarLeft, mdiLock, mdiLogout, mdiMenu, mdiMinus, mdiWeatherNight, mdiPackageVariant, mdiPaperclip, mdiPencil, mdiAirplaneTakeoff, mdiAirplaneLanding, mdiPlus, mdiRefresh, mdiRoutes, mdiScale, mdiMagnify, mdiCog, mdiShield, mdiShieldLock, mdiShieldAlert, mdiWeatherSunny, mdiDelete, mdiAccount, mdiAccountGroup, mdiClose, mdiTrendingUp, mdiTrendingDown, mdiTruck, mdiStore } from '@mdi/js'
import { mdiIcon } from './utils/mdiIcon'

const md = (path) => mdiIcon(path)

export const mdiIcons = {
  AirTrafficControl: md(mdiRadar),
  AlertCircle: md(mdiAlertCircle),
  AlertTriangle: md(mdiAlert),
  Api: md(mdiApi),
  ArrowsExchange: md(mdiSwapHorizontal),
  Bell: md(mdiBell),
  Book: md(mdiBookOpen),
  CheckCheck: md(mdiCheckAll),
  CalendarEvent: md(mdiCalendarMonth),
  Camera: md(mdiCamera),
  ChartBar: md(mdiChartBar),
  ChartPie: md(mdiChartPie),
  Check: md(mdiCheck),
  CheckCircle: md(mdiCheckCircle),
  ChevronRight: md(mdiChevronRight),
  ClipboardList: md(mdiClipboardList),
  Close: md(mdiClose),
  Code: md(mdiCodeTags),
  CrownFilled: md(mdiCrown),
  Cog: md(mdiCog),
  Download: md(mdiDownload),
  Eye: md(mdiEye),
  File: md(mdiFile),
  FileDescription: md(mdiFileDocument),
  FileExport: md(mdiFileExport),
  FileInvoice: md(mdiReceiptText),
  FileUpload: md(mdiFileUpload),
  Forklift: md(mdiForklift),
  Gauge: md(mdiGauge),
  Inbox: md(mdiInbox),
  Info: md(mdiInformation),
  Key: md(mdiKey),
  LayoutGrid: md(mdiViewGrid),
  LayoutSidebarFilled: md(mdiPageLayoutSidebarLeft),
  Lock: md(mdiLock),
  Logout: md(mdiLogout),
  Menu: md(mdiMenu),
  Minus: md(mdiMinus),
  Moon: md(mdiWeatherNight),
  Package: md(mdiPackageVariant),
  Paperclip: md(mdiPaperclip),
  Pencil: md(mdiPencil),
  PlaneDeparture: md(mdiAirplaneTakeoff),
  PlaneLanding: md(mdiAirplaneLanding),
  Plus: md(mdiPlus),
  Refresh: md(mdiRefresh),
  Route: md(mdiRoutes),
  Scale: md(mdiScale),
  Search: md(mdiMagnify),
  Send: md(mdiSend),
  Settings: md(mdiCog),
  Shield: md(mdiShield),
  ShieldLock: md(mdiShieldLock),
  ShieldAlert: md(mdiShieldAlert),
  Sun: md(mdiWeatherSunny),
  ThLarge: md(mdiViewGrid),
  Pallet: md(mdiShippingPallet),
  Trash: md(mdiDelete),
  TrendingDown: md(mdiTrendingDown),
  TrendingUp: md(mdiTrendingUp),
  Truck: md(mdiTruck),
  User: md(mdiAccount),
  Users: md(mdiAccountGroup),
  X: md(mdiClose),
  BuildingStore: md(mdiStore)
}